export const GET_INSPIRATION = "GET_INSPIRATION"
export const GET_INSPIRATION_OK = "GET_INSPIRATION_OK"
export const GET_INSPIRATION_FAIL = "GET_INSPIRATION_FAIL"

export const DO_CONTACT = "DO_CONTACT"
export const DO_CONTACT_OK = "DO_CONTACT_OK"
export const DO_CONTACT_FAIL = "DO_CONTACT_FAIL"

export const GET_ARTISTS = "GET_ARTISTS"
export const GET_ARTISTS_OK = "GET_ARTISTS_OK"
export const GET_ARTISTS_FAIL = "GET_ARTISTS_FAIL"