export const GET_MESSAGES = "GET_MESSAGES"
export const GET_MESSAGES_OK = "GET_MESSAGES_OK"
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL"

export const DO_CONTACT = "DO_CONTACT"
export const DO_CONTACT_OK = "DO_CONTACT_OK"
export const DO_CONTACT_FAIL = "DO_CONTACT_FAIL"

